export const POSITION_LEVELS: { [key: string]: number } = {
  "Partner": 5,
  "Principal": 4,
  "Specialist Director": 3,
  "Director": 3,
  "Senior Specialist Lead - Consulting Only": 2,
  "Senior Manager": 2,
  "Specialist Lead - Consulting Only": 1, 
  "Manager": 1, 
  "Senior Assistant": 0,
  "Team Assistant": 0,
  "Personal Assistant": 0,
  "Senior Consultant": 0,
  "Consultant": 0,
  "Analyst": 0,
  "Graduate": 0,
  "Undergraduate": 0,
}

export const TALENT_GROUPS: string[] = [
  "All",
  "Platform & Product Eng",
  "Operations Transformation",
  "Cloud Advisory",
  "Digital Banking",
  "Cross Industry",
  "Quality Eng",
  "Cloud Engineering",
  "Digital Workplace",
  "Operate",
  "Integration Eng",
  "Cloud Security & Network Engineering",
  "Insurance",
];